"""IEEE two-column figures for the PinPoint relevance-version audit.

All plotted statistics are read from --results (default results/reproduced), regenerated by src/audit.
No new inference is run. Figure 1(b) shows the real matched group selected by the fixed rule in
src/audit/case.py (results/reproduced/case.json).
"""
from pathlib import Path
import csv, json, textwrap
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Rectangle

import argparse
ROOT = Path(__file__).resolve().parents[2]  # repository root
_ap = argparse.ArgumentParser()
_ap.add_argument("--results", default=str(ROOT / "results" / "reproduced"), help="directory with regenerated results")
_ap.add_argument("--figdir", default=str(ROOT / "paper" / "figures"))
_args = _ap.parse_args()
SD, FIG = Path(_args.results), Path(_args.figdir)
FIG.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.family": "sans-serif", "font.sans-serif": ["DejaVu Sans"],
    "font.size": 7, "axes.labelsize": 7, "axes.titlesize": 7.5,
    "xtick.labelsize": 6.5, "ytick.labelsize": 6.5, "legend.fontsize": 6.5,
    "pdf.fonttype": 42, "axes.spines.top": False, "axes.spines.right": False,
    "legend.frameon": False, "axes.linewidth": 0.6,
    "xtick.major.width": 0.6, "ytick.major.width": 0.6,
})
BLUE, GRAY, ORANGE, LIGHT = "#0072B2", "#6E6E6E", "#D55E00", "#BBBBBB"
COL, FULL = 3.5, 7.16  # IEEE column / text width in inches

summary = list(csv.DictReader((SD / "summary.csv").open()))
contrasts = list(csv.DictReader((SD / "model_contrasts.csv").open()))
sel = split = json.loads((SD / "frame_summary.json").read_text())

METHODS = list(dict.fromkeys(r["method"] for r in summary))
NAMES = ["S1", "S1 reranked", "S2", "MetaCLIP2 Combined", "MetaCLIP2 Image-only",
         "MetaCLIP2 Text-only", "MetaCLIP2 SLERP"]
assert len(METHODS) == 7
SHORT = dict(zip(METHODS, NAMES))
# Display order: descending old AP@10 (identical under current labels), matching Table I.
_order = sorted(range(7), key=lambda i: -float(next(x for x in summary if x["domain"] == "current_fixed"
                and x["stratum"] == "all344" and x["metric"] == "AP10" and x["method"] == METHODS[i])["old"]))
PAIR_S1_RERANK = {METHODS[0], METHODS[1]}
METHODS = [METHODS[i] for i in _order]; NAMES = [NAMES[i] for i in _order]


def get(m, st, metric, dom="current_fixed"):
    return next(x for x in summary if x["domain"] == dom and x["stratum"] == st
                and x["metric"] == metric and x["method"] == m)


def panel(ax, s, dx=-0.02, dy=1.02):
    ax.text(dx, dy, s, transform=ax.transAxes, weight="bold", fontsize=8, va="bottom", ha="right")


def save(fig, name):
    fig.savefig(FIG / f"{name}.pdf")
    fig.savefig(FIG / f"{name}.png", dpi=300)
    plt.close(fig)


# ---------------------------------------------------------------- Figure 1
# (a) audit design; (b) real case chosen by the fixed rule in src/audit/case.py
case = json.loads((SD / "case.json").read_text())
fig = plt.figure(figsize=(FULL, 3.45))
axA = fig.add_axes([0.0, 0.0, 0.33, 0.93]); axA.axis("off"); axA.set(xlim=(0, 1), ylim=(0, 1))
axB = fig.add_axes([0.345, 0.0, 0.655, 0.93]); axB.axis("off"); axB.set(xlim=(0, 1), ylim=(0, 1))
axA.text(0.0, 1.03, "(a) Fixed-output audit", weight="bold", fontsize=7.5, va="top")
axB.text(0.0, 1.03, f"(b) Real matched group from the public release files (group {case['case_group']})",
         weight="bold", fontsize=7.5, va="top")


def box(ax, x, y, w, h, t, fc="#EEF3F7", fs=6.0):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.006,rounding_size=0.015",
                                fc=fc, ec="#AAB6BF", lw=0.6))
    ax.text(x + w / 2, y + h / 2, t, ha="center", va="center", fontsize=fs, linespacing=1.25)


def arr(ax, a, b, c=GRAY):
    ax.annotate("", xy=b, xytext=a, arrowprops=dict(arrowstyle="->", color=c, lw=0.8))


box(axA, 0.02, 0.74, 0.44, 0.15, "Fixed request\n(instruction + reference)")
box(axA, 0.54, 0.74, 0.44, 0.15, "Fixed cached ranking $R_q$\n(released run, top-50)")
arr(axA, (0.465, 0.815), (0.535, 0.815))
box(axA, 0.02, 0.47, 0.44, 0.14, "Old positives $Y^{old}_q$", "#F2F2F2")
box(axA, 0.54, 0.47, 0.44, 0.14, "Current positives $Y^{cur}_q$", "#E4F0F8")
arr(axA, (0.70, 0.735), (0.28, 0.615)); arr(axA, (0.76, 0.735), (0.76, 0.615))
box(axA, 0.02, 0.21, 0.44, 0.14, "$f(R_q, Y^{old}_q, C)$", "#F2F2F2")
box(axA, 0.54, 0.21, 0.44, 0.14, "$f(R_q, Y^{cur}_q, C)$", "#E4F0F8")
arr(axA, (0.24, 0.465), (0.24, 0.355)); arr(axA, (0.76, 0.465), (0.76, 0.355))
axA.text(0.50, 0.28, "$\\Delta$", ha="center", va="center", fontsize=7.5, color=BLUE)
axA.text(0.0, 0.0,
         f"Same candidate domain $C$ ({109600:,} IDs) and metric\ncode for both versions. Matched frame: "
         f"{sel['eligible_groups']} groups,\n{sel['eligible_queries']:,} queries; {split['split']} lose a shared positive set.",
         fontsize=6.3, va="bottom", linespacing=1.3)

COLORS = {"both": ("#555555", "white"), "old_only": ("#BBBBBB", "#222222"),
          "current_only": (BLUE, "white"), "none": ("white", "#777777")}
qs = case["queries"]
x0, w, gap, top = 0.43, 0.022, 0.004, 0.84
rowh = 0.09
axB.text(0.0, top + 0.035, "Instruction (unchanged across releases)", fontsize=6.3, color=GRAY)
axB.text(x0, top + 0.035, "Image-only top-10 (all six)", fontsize=6.3, color=GRAY)
axB.text(0.74, top + 0.035, "AP@10 old $\\rightarrow$ current", fontsize=6.3, color=GRAY)
axB.text(0.74, top - 0.005, "Image-only", fontsize=6.2, color=GRAY)
axB.text(0.88, top - 0.005, "S1 reranked", fontsize=6.2, color=GRAY)
for i in range(10):
    axB.text(x0 + i * (w + gap) + w / 2, top - 0.005, str(i + 1), ha="center", fontsize=6.0, color=GRAY)


def short(s, n=44):
    return s if len(s) <= n else s[: n - 1] + "…"


for k, q in enumerate(qs):
    y = top - 0.075 - k * rowh
    changed = q["positives_old"] != q["positives_current"]
    axB.text(0.0, y + rowh * 0.36, textwrap.fill(q["instruction"], 42), fontsize=6.0, va="center", linespacing=1.05,
             color=(ORANGE if changed else "#222222"), weight=("bold" if changed else "normal"))
    for i, stt in enumerate(q["top10_status"]):
        fc, tc = COLORS[stt]
        axB.add_patch(Rectangle((x0 + i * (w + gap), y), w, rowh * 0.72, fc=fc, ec="#999999", lw=0.4))
    si, sr = q["scores"]["MetaCLIP2 Image-only"], q["scores"]["S1 reranked"]
    axB.text(0.74, y + rowh * 0.35, f"{si['AP10_old']:.2f} $\\rightarrow$ {si['AP10_new']:.2f}", fontsize=6.3, va="center",
             color=(ORANGE if abs(si['AP10_new'] - si['AP10_old']) > 1e-12 else "#222222"))
    axB.text(0.88, y + rowh * 0.35, f"{sr['AP10_old']:.2f} $\\rightarrow$ {sr['AP10_new']:.2f}", fontsize=6.3, va="center",
             color=(ORANGE if abs(sr['AP10_new'] - sr['AP10_old']) > 1e-12 else "#222222"))
ly = top - 0.075 - len(qs) * rowh + 0.005
legend = [("both", "positive in both versions"), ("old_only", "positive only in old version"),
          ("current_only", "positive only in current version"), ("none", "not listed")]
shown = {st for q in qs for st in q["top10_status"]}
legend = [x for x in legend if x[0] in shown]
for j, (k, lab) in enumerate(legend):
    fc, _ = COLORS[k]
    xx = [0.0, 0.3, 0.62, 0.85][j]
    axB.add_patch(Rectangle((xx, ly), 0.018, 0.04, fc=fc, ec="#999999", lw=0.4))
    axB.text(xx + 0.024, ly + 0.02, lab, fontsize=6.1, va="center")
ri, rr = case["case_range_image_only"], case["case_range_S1_reranked"]
axB.text(0.0, 0.0, f"Group AP@10 range: Image-only {ri['old']:.2f} $\\rightarrow$ {ri['new']:.2f}, S1 reranked "
         f"{rr['old']:.2f} $\\rightarrow$ {rr['new']:.2f}.\nOrange rows: positive list replaced in the current release.\n"
         "Requests are unchanged across releases; semantic equivalence within the group is not established.",
         fontsize=6.3, va="bottom", linespacing=1.3)
save(fig, "fig1_design_case")

# ---------------------------------------------------------------- Figure 2: quality dumbbell
fig, ax = plt.subplots(figsize=(COL, 2.15)); fig.subplots_adjust(left=0.33, right=0.97, top=0.88, bottom=0.18)
y = np.arange(7)
old = [float(get(m, "all344", "AP10")["old"]) for m in METHODS]
new = [float(get(m, "all344", "AP10")["new"]) for m in METHODS]
for i in range(7):
    ax.plot([old[i], new[i]], [i, i], color=LIGHT, lw=1, zorder=1)
ax.scatter(old, y, s=18, fc="white", ec=GRAY, lw=0.8, label="Old judgments", zorder=3)
ax.scatter(new, y, s=16, marker="s", color=BLUE, label="Current judgments", zorder=3)
ax.set(yticks=y, yticklabels=NAMES, xlim=(0, 0.33), ylim=(6.6, -0.6), xlabel="Query-mean AP@10")
ax.grid(axis="x", color="#EEEEEE", lw=0.5)
ax.legend(loc="lower right", bbox_to_anchor=(1.0, 1.0), ncol=2, handletextpad=0.3, columnspacing=1.0)
save(fig, "fig2_quality")

# ---------------------------------------------------------------- Figure 3: the two main findings
# (a) S1 reranking advantage, old vs current, three populations (robustness.json)
# (b) public evaluator's sensitivity metric, rank old -> current, fixed outputs (evaluator_sensitivity.json)
RB = json.loads((SD / "robustness.json").read_text())
EV = json.loads((SD / "evaluator_sensitivity.json").read_text())
fig = plt.figure(figsize=(FULL, 2.3))
a = fig.add_axes([0.125, 0.19, 0.30, 0.70])
b = fig.add_axes([0.655, 0.19, 0.14, 0.70])
pops = [("frame_2091", "Matched groups\n(2,091 queries)"), ("wider_non_frame", "Other unchanged\n(2,134 queries)"),
        ("wider_all", "All unchanged\n(4,225 queries)")]
for i, (k, lab) in enumerate(pops):
    for j, (v, c, mk) in enumerate((("adv_old", GRAY, "o"), ("adv_new", BLUE, "s"))):
        e, lo, hi = RB[k][v]
        yy = i + (-0.14 if j == 0 else 0.14)
        a.errorbar(e, yy, xerr=[[e - lo], [hi - e]], fmt=mk, color=c, ms=3.5, capsize=2, lw=0.9,
                   mfc=("white" if j == 0 else c), label=(("Old labels", "Current labels")[j] if i == 0 else None))
a.set(yticks=range(3), yticklabels=[p[1] for p in pops], ylim=(2.6, -0.6), xlim=(0, 0.085), xticks=[0, 0.02, 0.04, 0.06, 0.08])
a.set_xlabel("S1 reranking advantage in AP@10 (95% interval)", fontsize=6.8)
a.grid(axis="x", color="#EEEEEE", lw=0.5)
a.legend(loc="lower right", fontsize=6.3, handletextpad=0.3)
a.set_title("(a) Improvement size", loc="left", fontsize=7.5, weight="bold", pad=6)

runs = ["S1 reranked", "S1", "S2", "MetaCLIP2 Combined", "MetaCLIP2 SLERP", "MetaCLIP2 Text-only", "MetaCLIP2 Image-only"]
flip = [f for f in EV["sign_flips"] if f["metric"] == "P10" and f["both_intervals_exclude_zero"]]
hl = {x for f in flip for x in (f["a"], f["b"])}
o, n = EV["sensitivity_order"]["P10_old"], EV["sensitivity_order"]["P10_new"]
for r in runs:
    c = ORANGE if r in hl else ("#444444" if r == "MetaCLIP2 Image-only" else BLUE)
    ro, rn = o.index(r) + 1, n.index(r) + 1
    vo, vn = EV["runs"][r]["P10"]["old"][0], EV["runs"][r]["P10"]["new"][0]
    b.plot([0, 1], [ro, rn], color=c, lw=(1.5 if r in hl else 0.9), marker="o", ms=3.2, zorder=3 if r in hl else 2)
    nm = r.replace("MetaCLIP2 ", "MC2 ")
    b.text(-0.08, ro, f"{nm}  {vo:.3f}", ha="right", va="center", fontsize=6.2, color=c)
    b.text(1.08, rn, f"{vn:.3f}  {nm}", ha="left", va="center", fontsize=6.2, color=c)
b.set(xlim=(0, 1), ylim=(7.5, 0.5), xticks=[0, 1], yticks=[])
b.set_xticklabels(["Old labels", "Current labels"], fontsize=6.5)
for sp in ("left", "right", "top"):
    b.spines[sp].set_visible(False)
b.set_title("(b) Evaluator sensitivity rank (1 = largest P@10 range)", fontsize=7.5, weight="bold", pad=6)
save(fig, "fig3_main_findings")

# ---------------------------------------------------------------- Figure 4: group range changes
fig, axs = plt.subplots(1, 3, figsize=(FULL, 2.0), sharey=True)
fig.subplots_adjust(left=0.165, right=0.975, top=0.86, bottom=0.2, wspace=0.12)
for j, (ax, st, t) in enumerate(zip(axs, ["all344", "split121", "other223"],
                                    ["All 344 groups", "121 split groups", "Other 223 groups"])):
    rr = [get(m, st, "AP_range") for m in METHODS]
    v = np.array([float(x["delta"]) for x in rr]); lo = np.array([float(x["ci_low"]) for x in rr])
    hi = np.array([float(x["ci_high"]) for x in rr])
    ax.errorbar(v, y, xerr=[v - lo, hi - v], fmt="o", color=BLUE, capsize=1.8, ms=2.8, lw=0.8)
    ax.axvline(0, color=LIGHT, lw=0.6)
    ax.set(xlim=(-0.09, 0.08), xticks=[-0.08, -0.04, 0, 0.04, 0.08], ylim=(6.6, -0.6), yticks=y)
    ax.set_title(t, fontsize=7); ax.grid(axis="x", color="#EEEEEE", lw=0.5)
    panel(ax, "abc"[j], dx=-0.01, dy=1.03)
axs[0].set_yticklabels(NAMES)
fig.text(0.56, 0.03, "Change in mean within-group AP@10 range (current $-$ old), paired 95% interval",
         ha="center", fontsize=7)
save(fig, "fig4_ranges")
print("figures written to", FIG)
